# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
