# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel', '0004_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activity'},
        ),
    ]
