# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionsUsers',
            new_name='SubscriptionUser',
        ),
    ]
