# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('in_progress', 'IN_PROGRESS'), ('finished', 'FINISHED')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
