# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('finished', 'finished')], max_length=255),
        ),
    ]
