# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licences', '0002_auto_20190309_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AddField(
            model_name='licences',
            name='status',
            field=models.CharField(choices=[('in_progress', 'IN_PROGRESS'), ('finished', 'FINISHED')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
