# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licences', '0003_auto_20190309_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licences',
            old_name='Contractor_name',
            new_name='name',
        ),
    ]
