# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licences', '0004_auto_20190309_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licences',
            options={'ordering': ('-expiry_date',), 'verbose_name_plural': 'Licences'},
        ),
    ]
